server:
  port: 8083
spring:
  application:
    name: springcloud-provider-register #对应着erueka的Application的名字

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-register-8083 #修改监控页面上默认显示信息，

# actuator
info:
  app.name: or-springcloud
  company.name: or-learn
  people.department: exploit、develop
  number: 1人
